baseURL = 'https://houjoe.me/'
languageCode = 'zh-cn'
title = "侯杰的个人博客"
theme = 'PaperMod'

# 启用 Emoji 支持
enableEmoji = true

# 作者信息
[author]
name = "侯杰"

[params]
# 网站描述
description = "记录学习笔记、技术思考和生活感悟"
# 默认主题模式
defaultTheme = "auto"
# 显示阅读时间
ShowReadingTime = true
# 显示分享按钮
ShowShareButtons = true
# 显示文章目录
ShowToc = true
# 显示面包屑导航
ShowBreadCrumbs = true
# 显示代码复制按钮
ShowCodeCopyButtons = true

# 社交链接
socialIcons = [
    { name = "github", url = "https://github.com/yourusername" }
]

# 菜单配置
[menu]
[[menu.main]]
identifier = "posts"
name = "文章"
url = "/posts/"
weight = 10

[[menu.main]]
identifier = "about"
name = "关于"
url = "/about/"
weight = 20
